apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shop
  name: shop-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: shop-deployment
    spec:
      containers:
        - image: mairaafreitas/personal-projects:shop-3
          name: shop
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 3
